"""Adding users table

Revision ID: 6208b36f9b21
Revises: 53c6ed588aaf
Create Date: 2018-04-04 10:50:16.098365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6208b36f9b21'
down_revision = '53c6ed588aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('updated_on', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
    op.drop_column('users', 'username')
    op.drop_column('users', 'updated_on')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_column('users', 'created_on')
    # ### end Alembic commands ###
